### ISSUE TITLE
W1. Project file structure

### ISSUE THREAD

**Issue by balazs-gabonyi** [codingmentor/eszkoznyilvantarto#6]
# DOD
- [x] Directory structure is well organized to hold all subprojects
- [x] All files needed files are git added (as of now)
- [x] All files uneeded files are git ignored (as of now)
Should be done until WED evening

# Project breakdown
- Registry - Enterprise app (JPA)
- Browser - Web app (JMS)
- MessageDefinition - Java SE app (JSE)
- Client - Java SE app (JSE)
- IntegrationTest Java SE app (JSE)

# Project Phases
## Project setup phase1
- [x] create project
- [x] select WildFly app server
- [x] add .gitignore
- [x] delete unused auto generated files
- [x] indent poms
## Project setup phase2
- [x] reorder parent project modules to: ejb, web, ear
- [x] make EJB a dependency of WEB
- [x] set source/target version to 1.8
- [x] set beans.xml discovery mode to: ALL in WEB project
- [x] add beans.xml to EJB project
## Project setup phase3
- [x] set persistence xml in accordance with WildFly datasource
## Project setup phase4
- [x] Set MessageDefinition to be a dependency in Registry and Browser

**Comment by muranyibence** [comment]
Sonar check done, sonar links:
[MessageDefinition](http://sonar.codingmentor.xyz/overview?id=8637)
[Registry](http://sonar.codingmentor.xyz/overview?id=8633)
[IntegrationTest](http://sonar.codingmentor.xyz/overview?id=8632)
[Client](http://sonar.codingmentor.xyz/overview?id=8631)
[Browser](http://sonar.codingmentor.xyz/overview?id=8630)

**Comment by muranyibence** [comment]
Ready to review, pull request:
[Feature/project setup](https://github.com/codingmentor/eszkoznyilvantarto/pull/11)
